### ISSUE TITLE
The priority of overloaded method (AddBody) was changed

### ISSUE THREAD

**Issue by tarukosu** [Unity3dAzure/RESTClient#4]
When I tried StorageServicesDemo with latest RESTClient(4f985e0ed3becd423a7d241ba34fb692ea136a70), an authentication error happend.
https://github.com/Unity3dAzure/StorageServicesDemo

The reason is that this commit(d563bb066f50c7dc0004ec0ee69d72563c4d8c51) adds an default argument to AddBody.

BlobService.cs calls AddBody method.
https://github.com/Unity3dAzure/StorageServices/blob/f1321b3665839b8906516ca4327e9648c6743851/BlobService.cs#L130

Before this commit(d563bb066f50c7dc0004ec0ee69d72563c4d8c51), BlobService.cs refers to this method. https://github.com/Unity3dAzure/RESTClient/blob/53700e23e6c4f343621c6c110f99a985e4621730/http/RestRequest.cs#L42
After the commit, however, BlobService.cs refers to this method.
https://github.com/Unity3dAzure/RESTClient/blob/4f985e0ed3becd423a7d241ba34fb692ea136a70/http/RestRequest.cs#L52

**Comment by rafek** [comment]
I've checked that today as well and yes. It breaks the scenario for `byte[]` array being passed for upload (without specifying `isChunked` explicitly.

So the workaround I guess would be to explicitly provide `false` for the third parameter. But that would need fixing anyway.

**Comment by rafek** [comment]
@deadlyfingers I guess this one can be closed now.
